### ISSUE TITLE
Spider tool can't crawl base 

### ISSUE THREAD

**Issue by peersky** [compound-finance/comet#825]
Obviously because RPC is defined by `INFURA_KEY` while Infura does [not support base yet](https://docs.infura.io/networks/base). 

<img width="1005" alt="image" src="https://github.com/compound-finance/comet/assets/61459744/9e7b9c58-6294-437f-9a0d-190bcc66f3f8">

```
An unexpected error occurred:

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/Users/timoz/OZGit/compound-monitoring-v3/address-generator/comet/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/timoz/OZGit/compound-monitoring-v3/address-generator/comet/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/Users/timoz/OZGit/compound-monitoring-v3/address-generator/comet/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (/Users/timoz/OZGit/compound-monitoring-v3/address-generator/comet/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/timoz/OZGit/compound-monitoring-v3/address-generator/comet/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/timoz/OZGit/compound-monitoring-v3/address-generator/comet/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

It would be more reliable if `RPC_URL` could be supplied generally, instead of relying on a particular provider.

**Comment by peersky** [comment]
Checked the hardhat code. It's just missing in readme that for base one needs to define `QUICKNODE_KEY`
